name: Deploy To EC2

on:
  push:
    branches:
      - deploy/ljr

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github repository에서 파일 가져오기
        uses: actions/checkout@v4

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.properties 파일 생성
        run: |
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: WAR 파일 이름을 metal-wallet-server.war로 변경
        run: mv build/libs/*.war build/libs/metal-wallet-server.war

      - name: WAR 파일이 존재하는지 확인
        run: ls build/libs/metal-wallet-server.war

      - name: SCP로 EC2에 빌드된 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: build/libs/metal-wallet-server.war
          target: /home/ubuntu/metal-wallet-server/tobe

      - name: EC2에서 서버 디렉토리 업데이트 및 서버 재시작
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            rm -rf /home/ubuntu/metal-wallet-server/current
            mkdir /home/ubuntu/metal-wallet-server/current
            mv /home/ubuntu/metal-wallet-server/tobe/build/libs/metal-wallet-server.war /home/ubuntu/metal-wallet-server/current/metal-wallet-server.war
            sudo cp /home/ubuntu/metal-wallet-server/current/metal-wallet-server.war /opt/tomcat/latest/webapps/metal-wallet-server.war
            cd /home/ubuntu/metal-wallet-server/current
            sudo fuser -k -n tcp 8080 || true
            sudo systemctl restart tomcat